services:
  nacos:
    image: nacos/nacos-server:v3.1.1
    container_name: nacos
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos
    ports:
      - "18080:8080"
      - "18848:8848"
      - "19848:9848"
    restart: unless-stopped